In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


In [2]:
# from google.colab import drive 
# drive.mount('/content/gdrive')

In [3]:
# Feature names from the file kddcup.names file to be used as cols heading
col_names = ["duration","protocol_type","service","flag","src_bytes",
    "dst_bytes","land","wrong_fragment","urgent","hot","num_failed_logins",
    "logged_in","num_compromised","root_shell","su_attempted","num_root",
    "num_file_creations","num_shells","num_access_files","num_outbound_cmds",
    "is_host_login","is_guest_login","count","srv_count","serror_rate",
    "srv_serror_rate","rerror_rate","srv_rerror_rate","same_srv_rate",
    "diff_srv_rate","srv_diff_host_rate","dst_host_count","dst_host_srv_count",
    "dst_host_same_srv_rate","dst_host_diff_srv_rate","dst_host_same_src_port_rate",
    "dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate",
    "dst_host_rerror_rate","dst_host_srv_rerror_rate","label"]

df = pd.read_csv("kddcup.data_10_percent_corrected", header=None, names = col_names)

# df=pd.read_csv('/content/gdrive/My Drive/data/kddcup.data_10_percent_corrected')
df.head()

duration protocol_type service flag  src_bytes  dst_bytes  land  \
0         0           tcp    http   SF        181       5450     0   
1         0           tcp    http   SF        239        486     0   
2         0           tcp    http   SF        235       1337     0   
3         0           tcp    http   SF        219       1337     0   
4         0           tcp    http   SF        217       2032     0   

   wrong_fragment  urgent  hot  ...  dst_host_srv_count  \
0               0       0    0  ...                   9   
1               0       0    0  ...                  19   
2               0       0    0  ...                  29   
3               0       0    0  ...                  39   
4               0       0    0  ...                  49   

   dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                     1.0                     0.0   
1                     1.0                     0.0   
2                     1.0                     0.0   
3                     1.0                     0.0   
4                     1.0                     0.0   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.11                          0.0   
1                         0.05                          0.0   
2                         0.03                          0.0   
3                         0.03                          0.0   
4                         0.02                          0.0   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                   0.0                       0.0                   0.0   
1                   0.0                       0.0                   0.0   
2                   0.0                       0.0                   0.0   
3                   0.0                       0.0                   0.0   
4                   0.0                       0.0                   0.0   

   dst_host_srv_rerror_rate    label  
0                       0.0  normal.  
1                       0.0  normal.  
2                       0.0  normal.  
3                       0.0  normal.  
4                       0.0  normal.  

[5 rows x 42 columns]

In [4]:
df.shape

(494021, 42)

In [6]:
df['label'].unique()

array(['normal.', 'buffer_overflow.', 'loadmodule.', 'perl.', 'neptune.',
       'smurf.', 'guess_passwd.', 'pod.', 'teardrop.', 'portsweep.',
       'ipsweep.', 'land.', 'ftp_write.', 'back.', 'imap.', 'satan.',
       'phf.', 'nmap.', 'multihop.', 'warezmaster.', 'warezclient.',
       'spy.', 'rootkit.'], dtype=object)

In [7]:
newlabeldf=df['label'].replace({ 'normal.' : 0, 'neptune.' : 1 ,'back.': 1, 'land.': 1, 'pod.': 1, 'smurf.': 1, 'teardrop.': 1,'mailbomb.': 1, 'apache2.': 1, 'processtable.': 1, 'udpstorm.': 1, 'worm.': 1,
                           'ipsweep.' : 2,'nmap.' : 2,'portsweep.' : 2,'satan.' : 2,'mscan.' : 2,'saint.' : 2
                           ,'ftp_write.': 3,'guess_passwd.': 3,'imap.': 3,'multihop.': 3,'phf.': 3,'spy.': 3,'warezclient.': 3,'warezmaster.': 3,'sendmail.': 3,'named.': 3,'snmpgetattack.': 3,'snmpguess.': 3,'xlock.': 3,'xsnoop.': 3,'httptunnel.': 3,
                           'buffer_overflow.': 4,'loadmodule.': 4,'perl.': 4,'rootkit.': 4,'ps.': 4,'sqlattack.': 4,'xterm.': 4})
df['label'] = newlabeldf
#df['target'] = newlabeldf
print(df['label'].head())

0    0
1    0
2    0
3    0
4    0
Name: label, dtype: object


In [ ]:
df.info()

In [8]:

from sklearn.preprocessing import LabelEncoder,OneHotEncoder
le = LabelEncoder()
df['protocol_type'] = le.fit_transform(df['protocol_type'])
df['service']= le.fit_transform(df['service'])
df['flag'] = le.fit_transform(df['flag'])



In [9]:
X = df.iloc[:,:41]
y = df.iloc[:,-1].astype('int')

In [12]:
X.head()

duration  protocol_type  service  flag  src_bytes  dst_bytes  land  \
0         0              1       22     9        181       5450     0   
1         0              1       22     9        239        486     0   
2         0              1       22     9        235       1337     0   
3         0              1       22     9        219       1337     0   
4         0              1       22     9        217       2032     0   

   wrong_fragment  urgent  hot  ...  dst_host_count  dst_host_srv_count  \
0               0       0    0  ...               9                   9   
1               0       0    0  ...              19                  19   
2               0       0    0  ...              29                  29   
3               0       0    0  ...              39                  39   
4               0       0    0  ...              49                  49   

   dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                     1.0                     0.0   
1                     1.0                     0.0   
2                     1.0                     0.0   
3                     1.0                     0.0   
4                     1.0                     0.0   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.11                          0.0   
1                         0.05                          0.0   
2                         0.03                          0.0   
3                         0.03                          0.0   
4                         0.02                          0.0   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                   0.0                       0.0                   0.0   
1                   0.0                       0.0                   0.0   
2                   0.0                       0.0                   0.0   
3                   0.0                       0.0                   0.0   
4                   0.0                       0.0                   0.0   

   dst_host_srv_rerror_rate  
0                       0.0  
1                       0.0  
2                       0.0  
3                       0.0  
4                       0.0  

[5 rows x 41 columns]

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 34,test_size = 0.3)


In [14]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [18]:
from sklearn.ensemble import RandomForestClassifier
model1 = RandomForestClassifier(n_estimators=100, max_depth=10,random_state=0,class_weight='balanced')
model1.fit(X_train_scaled,y_train)

RandomForestClassifier(bootstrap=True, class_weight='balanced',
                       criterion='gini', max_depth=10, max_features='auto',
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=None, oob_score=False,
                       random_state=0, verbose=0, warm_start=False)

In [19]:
predict = model1.predict(X_test_scaled)


In [20]:
model1.score(X_test_scaled,y_test)

0.9993927412335449

In [21]:
model1.score(X_train_scaled,y_train)

0.999635642281689

In [22]:
from sklearn.metrics import confusion_matrix,recall_score,precision_score
print((confusion_matrix(y_test,predict)))

[[ 29073      1      0     54      2]
 [     9 117470      0      0      1]
 [    13      0   1254      0      0]
 [     7      1      0    305      0]
 [     2      0      0      0     15]]


In [23]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     29130
           1       1.00      1.00      1.00    117480
           2       1.00      0.99      0.99      1267
           3       0.85      0.97      0.91       313
           4       0.83      0.88      0.86        17

    accuracy                           1.00    148207
   macro avg       0.94      0.97      0.95    148207
weighted avg       1.00      1.00      1.00    148207



## Predicting actual 10% test data

In [24]:
df_test = pd.read_csv("kddcup.newtestdata_10_percent_unlabeled", header=None, names = col_names[:-1])
# df_test['protocol_type'] = le.fit_transform(df_test['protocol_type'])
# df_test['service']= le.fit_transform(df_test['service'])
# df_test['flag'] = le.fit_transform(df_test['flag'])


In [25]:
df_test.head()

duration protocol_type   service flag  src_bytes  dst_bytes  land  \
0         0           tcp      smtp   SF        829        327     0   
1         0           udp   private   SF        105        146     0   
2         0           udp   private   SF        105        146     0   
3         0           udp   private   SF        105        146     0   
4         0           tcp  ftp_data   SF         19          0     0   

   wrong_fragment  urgent  hot  ...  dst_host_count  dst_host_srv_count  \
0               0       0    0  ...               8                 113   
1               0       0    0  ...             255                 253   
2               0       0    0  ...             255                 254   
3               0       0    0  ...             255                 253   
4               0       0    0  ...             226                  46   

   dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                    0.88                    0.25   
1                    0.99                    0.01   
2                    1.00                    0.01   
3                    0.99                    0.01   
4                    0.19                    0.03   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.12                         0.02   
1                         0.00                         0.00   
2                         0.01                         0.00   
3                         0.00                         0.00   
4                         0.19                         0.04   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                   0.0                       0.0                   0.0   
1                   0.0                       0.0                   0.0   
2                   0.0                       0.0                   0.0   
3                   0.0                       0.0                   0.0   
4                   0.0                       0.0                   0.0   

   dst_host_srv_rerror_rate  
0                       0.0  
1                       0.0  
2                       0.0  
3                       0.0  
4                       0.0  

[5 rows x 41 columns]

In [26]:
df_test['protocol_type'] = le.fit_transform(df_test['protocol_type'])
df_test['service']= le.fit_transform(df_test['service'])
df_test['flag'] = le.fit_transform(df_test['flag'])

In [27]:
df_test.head()

duration  protocol_type  service  flag  src_bytes  dst_bytes  land  \
0         0              1       50     8        829        327     0   
1         0              2       46     8        105        146     0   
2         0              2       46     8        105        146     0   
3         0              2       46     8        105        146     0   
4         0              1       19     8         19          0     0   

   wrong_fragment  urgent  hot  ...  dst_host_count  dst_host_srv_count  \
0               0       0    0  ...               8                 113   
1               0       0    0  ...             255                 253   
2               0       0    0  ...             255                 254   
3               0       0    0  ...             255                 253   
4               0       0    0  ...             226                  46   

   dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                    0.88                    0.25   
1                    0.99                    0.01   
2                    1.00                    0.01   
3                    0.99                    0.01   
4                    0.19                    0.03   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.12                         0.02   
1                         0.00                         0.00   
2                         0.01                         0.00   
3                         0.00                         0.00   
4                         0.19                         0.04   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                   0.0                       0.0                   0.0   
1                   0.0                       0.0                   0.0   
2                   0.0                       0.0                   0.0   
3                   0.0                       0.0                   0.0   
4                   0.0                       0.0                   0.0   

   dst_host_srv_rerror_rate  
0                       0.0  
1                       0.0  
2                       0.0  
3                       0.0  
4                       0.0  

[5 rows x 41 columns]

In [28]:
predicted = model1.predict(df_test)

In [29]:
print(classification_report(y_test, predicted))

ValueError: Found input variables with inconsistent numbers of samples: [148207, 311079]